package io.yukti.engine.optimizer;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.yukti.catalog.ClasspathCatalogSource;
import io.yukti.core.api.Catalog;
import io.yukti.core.api.Optimizer;
import io.yukti.core.domain.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIf;

import java.math.BigDecimal;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Cross-validation: Java MILP vs Python MILP produce identical results.
 * Ensures the hybrid approach (Java for web, Python for bench) is mathematically consistent.
 *
 * <p>Requires {@code artifacts/bench/v1/bench-results-milp.json} to exist
 * (generated by {@code python yukti-milp/milp_baseline.py}).
 */
@Tag("cross-validation")
class MilpCrossValidationTest {

    private static final Path PYTHON_RESULTS = Path.of("artifacts", "bench", "v1", "bench-results-milp.json");
    private static final BigDecimal NET_TOLERANCE = new BigDecimal("1.00"); // $1 tolerance for float differences

    private Catalog catalog;
    private Optimizer milp;
    private Map<String, JsonNode> pythonRuns;

    static boolean pythonResultsExist() {
        return Files.exists(PYTHON_RESULTS);
    }

    @BeforeEach
    void setUp() throws Exception {
        catalog = new ClasspathCatalogSource("catalog/catalog-v1.json").load("1.0");
        milp = new MilpOptimizer();

        if (Files.exists(PYTHON_RESULTS)) {
            ObjectMapper mapper = new ObjectMapper();
            JsonNode root = mapper.readTree(PYTHON_RESULTS.toFile());
            pythonRuns = new LinkedHashMap<>();
            for (JsonNode run : root.get("runs")) {
                String key = run.get("profileId").asText() + "/" + run.get("goal").asText();
                pythonRuns.put(key, run);
            }
        }
    }

    @Test
    @EnabledIf("pythonResultsExist")
    void javaAndPythonProduceSameNetValues() {
        List<CrossValidationCase> cases = buildCases();
        int tested = 0;
        int matched = 0;
        StringBuilder mismatches = new StringBuilder();

        for (CrossValidationCase tc : cases) {
            String key = tc.profileId + "/" + tc.goal.name();
            JsonNode pythonRun = pythonRuns.get(key);
            if (pythonRun == null || "infeasible".equals(pythonRun.path("status").asText())) {
                continue;
            }

            OptimizationResult javaResult = milp.optimize(tc.request, catalog);
            BigDecimal javaNet = javaResult.getBreakdown().getNet().getAmount();
            BigDecimal pythonNet = BigDecimal.valueOf(pythonRun.get("netValueUsd").asDouble());

            tested++;
            BigDecimal diff = javaNet.subtract(pythonNet).abs();
            if (diff.compareTo(NET_TOLERANCE) <= 0) {
                matched++;
            } else {
                mismatches.append(String.format("  %s: Java=$%.2f Python=$%.2f diff=$%.2f%n",
                    key, javaNet, pythonNet, diff));
            }
        }

        assertTrue(tested > 0, "Should have tested at least one case");
        assertEquals(tested, matched,
            String.format("All %d tested runs should match within $%.2f tolerance:\n%s",
                tested, NET_TOLERANCE, mismatches));
    }

    @Test
    @EnabledIf("pythonResultsExist")
    void javaAndPythonSelectSamePortfolios() {
        List<CrossValidationCase> cases = buildCases();
        int tested = 0;
        int matched = 0;
        StringBuilder mismatches = new StringBuilder();

        for (CrossValidationCase tc : cases) {
            String key = tc.profileId + "/" + tc.goal.name();
            JsonNode pythonRun = pythonRuns.get(key);
            if (pythonRun == null || "infeasible".equals(pythonRun.path("status").asText())) {
                continue;
            }

            OptimizationResult javaResult = milp.optimize(tc.request, catalog);
            List<String> javaPortfolio = new ArrayList<>(javaResult.getPortfolioIds());
            Collections.sort(javaPortfolio);

            List<String> pythonPortfolio = new ArrayList<>();
            for (JsonNode id : pythonRun.get("portfolio")) {
                pythonPortfolio.add(id.asText());
            }
            Collections.sort(pythonPortfolio);

            tested++;
            if (javaPortfolio.equals(pythonPortfolio)) {
                matched++;
            } else {
                mismatches.append(String.format("  %s: Java=%s Python=%s%n",
                    key, javaPortfolio, pythonPortfolio));
            }
        }

        assertTrue(tested > 0, "Should have tested at least one case");
        // Allow some portfolio differences due to ties — check net values match instead
        double matchRate = (double) matched / tested * 100;
        assertTrue(matchRate >= 80.0,
            String.format("Portfolio match rate should be >= 80%%: %.1f%% (%d/%d)\n%s",
                matchRate, matched, tested, mismatches));
    }

    private List<CrossValidationCase> buildCases() {
        // Use baseline profiles that match BenchmarkHarness
        List<CrossValidationCase> cases = new ArrayList<>();

        Object[][] profiles = {
            {"light", false, Map.of(Category.GROCERIES, 3000., Category.DINING, 1500., Category.GAS, 1200., Category.OTHER, 2500.)},
            {"moderate", false, Map.of(Category.GROCERIES, 6000., Category.DINING, 3000., Category.GAS, 2400., Category.TRAVEL, 2000., Category.ONLINE, 1200., Category.OTHER, 5000.)},
            {"heavy", false, Map.of(Category.GROCERIES, 15000., Category.DINING, 6000., Category.GAS, 3600., Category.TRAVEL, 8000., Category.ONLINE, 3000., Category.OTHER, 10000.)},
            {"balanced", false, Map.of(Category.GROCERIES, 5000., Category.DINING, 2500., Category.GAS, 2000., Category.TRAVEL, 2500., Category.ONLINE, 1500., Category.OTHER, 4000.)},
            {"minimal", false, Map.of(Category.OTHER, 5000.)},
            {"high-net-worth", false, Map.of(Category.GROCERIES, 24000., Category.DINING, 12000., Category.GAS, 6000., Category.TRAVEL, 20000., Category.ONLINE, 6000., Category.OTHER, 20000.)},
        };

        for (Object[] p : profiles) {
            String id = (String) p[0];
            boolean monthly = (Boolean) p[1];
            @SuppressWarnings("unchecked")
            Map<Category, Double> spend = (Map<Category, Double>) p[2];

            Map<Category, Money> amounts = new EnumMap<>(Category.class);
            spend.forEach((cat, amt) -> amounts.put(cat, Money.usd(amt)));
            SpendProfile sp = new SpendProfile(monthly ? Period.MONTHLY : Period.ANNUAL, amounts);

            for (GoalType goal : List.of(GoalType.CASHBACK, GoalType.FLEX_POINTS, GoalType.PROGRAM_POINTS)) {
                UserGoal userGoal = goal == GoalType.PROGRAM_POINTS
                    ? new UserGoal(GoalType.PROGRAM_POINTS, Optional.of(RewardCurrencyType.AVIOS), List.of(), Map.of())
                    : UserGoal.of(goal);
                cases.add(new CrossValidationCase(id, goal,
                    new OptimizationRequest(sp, userGoal, UserConstraints.defaults(), Map.of())));
            }
        }
        return cases;
    }

    record CrossValidationCase(String profileId, GoalType goal, OptimizationRequest request) {}
}
